### ISSUE TITLE
Use Plugins Error

### ISSUE THREAD

**Issue by Miazzy** [cumulusclips/plugins#1]
ERROR: Plugin "plugins-master" is invalid and cannot be loaded.

> MacdeMacBook-Pro:plugins-master mac$ docker exec -it 7ea8 bash
> root@7ea83c8a1fe3:/# ls
> bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
> root@7ea83c8a1fe3:/# cd /var/www/html/
> root@7ea83c8a1fe3:/var/www/html# ls
> root@7ea83c8a1fe3:/var/www/html# cd ..
> root@7ea83c8a1fe3:/var/www# ls
> LICENSE.txt  README.txt  cc-admin  cc-content  cc-core  favicon.ico  html  index.php
> root@7ea83c8a1fe3:/var/www# cd cc-content/
> root@7ea83c8a1fe3:/var/www/cc-content# ls
> emails  languages  plugins  themes  uploads
> root@7ea83c8a1fe3:/var/www/cc-content# cd plugins/
> root@7ea83c8a1fe3:/var/www/cc-content/plugins# ls
> plugins-master
> root@7ea83c8a1fe3:/var/www/cc-content/plugins# cd plugins-master/
> root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master# ls
> Captcha  GoogleAnalytics  README.md
> root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master#

**Comment by Miazzy** [comment]
`MacdeMacBook-Pro:plugins-master mac$ docker exec -it 7ea8 bash
root@7ea83c8a1fe3:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@7ea83c8a1fe3:/# cd /var/www/html/
root@7ea83c8a1fe3:/var/www/html# ls
root@7ea83c8a1fe3:/var/www/html# cd ..
root@7ea83c8a1fe3:/var/www# ls
LICENSE.txt  README.txt  cc-admin  cc-content  cc-core  favicon.ico  html  index.php
root@7ea83c8a1fe3:/var/www# cd cc-content/
root@7ea83c8a1fe3:/var/www/cc-content# ls
emails  languages  plugins  themes  uploads
root@7ea83c8a1fe3:/var/www/cc-content# cd plugins/
root@7ea83c8a1fe3:/var/www/cc-content/plugins# ls
plugins-master
root@7ea83c8a1fe3:/var/www/cc-content/plugins# cd plugins-master/
root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master# ls
Captcha  GoogleAnalytics  README.md
root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master# 
`

**Comment by Miazzy** [comment]
> MacdeMacBook-Pro:plugins-master mac$ docker exec -it 7ea8 bash

> root@7ea83c8a1fe3:/# ls
> bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
> root@7ea83c8a1fe3:/# cd /var/www/html/
> root@7ea83c8a1fe3:/var/www/html# ls
> root@7ea83c8a1fe3:/var/www/html# cd ..
> root@7ea83c8a1fe3:/var/www# ls
> LICENSE.txt  README.txt  cc-admin  cc-content  cc-core  favicon.ico  html  index.php
> root@7ea83c8a1fe3:/var/www# cd cc-content/
> root@7ea83c8a1fe3:/var/www/cc-content# ls
> emails  languages  plugins  themes  uploads
> root@7ea83c8a1fe3:/var/www/cc-content# cd plugins/
> root@7ea83c8a1fe3:/var/www/cc-content/plugins# ls
> plugins-master
> root@7ea83c8a1fe3:/var/www/cc-content/plugins# cd plugins-master/
> root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master# ls
> Captcha  GoogleAnalytics  README.md
> root@7ea83c8a1fe3:/var/www/cc-content/plugins/plugins-master#

**Comment by mtado06** [comment]
It looks like you cloned the entire Plugins repo into your plugin directory. You're only supposed to include the specific plugin that you want.
